---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/gcpsoares/infra-deployments.git
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-test-env-branch
